#!/usr/bin/env node
/**
 * Stage the implementation's proxy-rule set for publication.
 *
 * The set as authored is prefix-free and named for the repo; what CE must receive is
 * a set NAMED for the alias (upload-artifact attaches it by name) whose routes live
 * under /api/<alias>/ (deploy-proxy-rules --path-prefix does that at sync time), plus
 * one generated rule the source must never carry: the /w/<alias>/* forwarder that
 * makes the harness host serve this implementation's assets same-origin (ADR-0001).
 *
 * Both edits happen on a COPY under $RUNNER_TEMP — the checkout is left untouched so a
 * re-run, or a second implementation in the same job, sees the same source it started with.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { parseDocument, stringify } from 'yaml'

/** Alias names CE or the harness already owns; an implementation may not take one. */
export const RESERVED_ALIASES = ['workflow', 'w', 'auth', '_bffless']

/** Alias grammar: lowercase, hyphen-separated, letter-initial — it becomes a hostname label. */
const ALIAS_RE = /^[a-z][a-z0-9-]*$/

/** The one rule this action generates. Authoring it by hand would be silently overwritten. */
const FORWARD_DIR = join('rules', '_custom', 'forward')
const FORWARD_FILE = 'get.rule.yaml'

const forwarderDescription = (alias) =>
  `Generated by bffless/publish-workflow: single-origin forwarding (ADR-0001) — /w/${alias}/[...path] ` +
  'on the harness host → the implementation alias. targetUrl is per-install until CE grows ' +
  'targetUrl: alias:// (bffless/ce#698).'

export function assertAlias(alias) {
  if (!alias) throw new Error('alias is required')
  if (RESERVED_ALIASES.includes(alias)) {
    throw new Error(`alias "${alias}" is reserved (${RESERVED_ALIASES.join(', ')})`)
  }
  if (!ALIAS_RE.test(alias)) {
    throw new Error(`alias "${alias}" is not a valid alias: expected ${ALIAS_RE}`)
  }
}

/**
 * @param {{ rulesDir: string, alias: string, targetUrl: string, outDir: string }} opts
 * @returns {Promise<string>} the staged directory (== opts.outDir)
 */
export async function prepareRules({ rulesDir, alias, targetUrl, outDir }) {
  assertAlias(alias)
  if (!targetUrl) {
    throw new Error(
      'target-url is required: the implementation alias host the forwarder points at ' +
        '(e.g. https://hello.j5s.dev). Required until bffless/ce#698 lands alias:// targets.',
    )
  }
  if (!existsSync(join(rulesDir, 'ruleset.yaml'))) {
    throw new Error(`not a rule set (no ruleset.yaml): ${rulesDir}`)
  }
  if (existsSync(join(rulesDir, FORWARD_DIR))) {
    throw new Error(
      `${rulesDir}/${FORWARD_DIR} exists in source: the /w/<alias>/* forwarder is generated ` +
        'by bffless/publish-workflow — delete the authored copy.',
    )
  }

  mkdirSync(dirname(outDir), { recursive: true })
  cpSync(rulesDir, outDir, { recursive: true, force: true })

  // Rewrite only `name:` — comments, key order and `description:` survive, so a `pull`
  // of the pushed set still diffs cleanly against the source it came from.
  const rulesetPath = join(outDir, 'ruleset.yaml')
  const doc = parseDocument(readFileSync(rulesetPath, 'utf8'))
  doc.set('name', alias)
  writeFileSync(rulesetPath, doc.toString())

  // An explicit `pathPattern:` is never touched by --path-prefix (CE CLI build.ts:
  // `manifest.pathPattern ?? applyPathPrefix(...)`), so /w/<alias>/* survives the sync.
  const forwardDir = join(outDir, FORWARD_DIR)
  mkdirSync(forwardDir, { recursive: true })
  writeFileSync(
    join(forwardDir, FORWARD_FILE),
    stringify({
      pathPattern: `/w/${alias}/*`,
      targetUrl,
      forwardCookies: true,
      order: 5,
      description: forwarderDescription(alias),
    }),
  )

  return outDir
}

/** Minimal `--flag value` parser — no deps, no clever aliasing. */
function parseArgs(argv) {
  const out = {}
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (!a.startsWith('--')) throw new Error(`unexpected argument: ${a}`)
    const value = argv[++i]
    if (value === undefined) throw new Error(`${a} needs a value`)
    out[a.slice(2)] = value
  }
  return out
}

export async function main(argv, out = console.log) {
  const args = parseArgs(argv)
  const dir = await prepareRules({
    rulesDir: args.rules,
    alias: args.alias,
    targetUrl: args['target-url'],
    outDir: args.out,
  })
  // Written to stdout so the composite step can redirect it into $GITHUB_OUTPUT.
  out(`dir=${dir}`)
  return dir
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2)).catch((e) => {
    console.error(`publish-workflow: ${e.message}`)
    process.exitCode = 1
  })
}

